.Dd July 24, 2021
.Dt INDEX 7

.Sh NAME
.Nm index
.Nd index to the InitKit™ Manual Pages

.Sh DESCRIPTION

This is the index to the InitKit™ Manual Pages, the authoritative reference on
the operation of the InitKit Init System.

.Ss System Manager's Manual

.Bl -tag
.It Xr initd 8
The InitKit Main Supervisor service.
.El
